name: Action Practice


on:
  push:
  

env:
  TZ: Asia/Shanghai

jobs:
  # a single job
  a-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: set chromedriver
        uses: nanasess/setup-chromedriver@v2
      - name: start browser

        run: |
          export DISPLAY=:99 
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Install Chrome
        run: |
          sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo apt update
          sudo apt-get install -y google-chrome-stable x11vnc fluxbox firefox-geckodriver
          pip install cloudflared

      - name: Start VNC server
        run: |
          x11vnc -display :99 -N -forever -shared &
          echo "VNC server started on port 5900"

      - name: Start Fluxbox
        run: |
          fluxbox &

      - name: Start Cloudflared tunnel
        run: |
          cloudflared tunnel --url http://localhost:5900 &
          sleep 10 # Wait for tunnel to be established
          echo "Cloudflared tunnel started, VNC server accessible via the generated URL"

       
      - name: Install requirements   
        run: |
          python3 -m pip install --upgrade pip
          pip3 install selenium requests beautifulsoup4 lxml asyncio aiohttp cryptography pycryptodome argparse opencv-python

      - name: Commit
        env:
          GIT_NAME: GitHub Actions[Bot]
          GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        
        run: |
          git config --local user.name $GIT_NAME
          git config --local user.email $GIT_EMAIL
          git pull
           
          
          git reset --mixed origin/main
          git add .
          git commit -m "Github action update at `date '+%Y-%m-%d %H:%M:%S'`."
          git push
